language: java
sudo: false
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - MAVEN_OPTS="-XX:MaxPermSize=256m -Xmx512m"
  - JAVA_OPTS="-XX:MaxPermSize=256m -Xmx512m"
jdk:
- oraclejdk8
services:
- mysql
script: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
before_install:
- mysql -e 'CREATE DATABASE mysql_db;'
deploy:
  provider: openshift
  user: "$EMAIL_ADDRESS"
  password:
    secure: TWk73Ysbb0gKB6WFcDhbgF+rvuLuy81/F3wXfzg64r+v87QAGtvCDtF5FTQRgqnIyu86QpLafy24xE/E5PLsQz23DMNUZ1Y5TsNY+pG7B5L3ghn6otI2HPns4OzRImuypx7dtzDcEaIRUc3eQYFLEEZ4sLNCus2IsMaYW1ZX9/XzhpZg8QjCFbGZTpW3Z1KJTa4XYyZo+o1PltcGa4R4A4vC/VgZk/TpUwzUSJN4j9d9nHBQJtqfyvHwCnhALlDfn+PZC2rUBIc1dj3lITQEMv0jd9kkxhxkHc4PH1/+32KXB2+z4k5nW5wXJG7sNB9Lmt3zfbrxu7CATJI4QOdxwJG07Qp0+YzmVIWEeHZ1HqmKuBxzIYykcYCbi70r0dguo9WXFmALrdZ2cH5ksVIM4pWLW06l2wx38S1P2LZSjCCHTrAY+0GxK4X7Vsp5jRyOlTIbHmsoenY050anNzs0J1cvAGr8tkUF+wZCf1nhmdnIlV14iwxsQC9+xLKoT0XZM4m5Cy+9EMGN5Psf6JO20lvegogsJINMszXsAAK56mNb6r07I4InVtvgU0LGeMOhzds/XJP1vHaHWfnRXr5k8JWkKuKGbNSi/PtVaPcVvZhIFGeQHBQGlPTgN7I3rCC5mNhuozNd7gl9mDhENhvy7rSfivlpjOv7Vxt3ULLM3Fs=
  app: "$APP_NAME"
  domain: "$DOMAIN_NAME"
  on:
    repo: lxisoft/test_Byta_ADT
